language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  - ruby-head
before_script:
  - mysql -e "CREATE USER 'dev'@'localhost';"
  - mysql -e "GRANT USAGE ON * . * TO  'dev'@'localhost' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;"
  - mysql -e "GRANT ALL PRIVILEGES ON  `dev\_%` . * TO  'dev'@'localhost';"
  - mysql -e "CREATE DATABASE dev__enginery;"
